### ISSUE TITLE
How can I change the animation duration?

### ISSUE THREAD

**Issue by MartinKolb1987** [subvisual/meteor-bender#5]
Hi. I‘ve got one question. Is it possible to change the animation duration? Thanks for your help!

**Comment by aadamsx** [comment]
Do you have this working with Autoform in your project by chance?

**Comment by MartinKolb1987** [comment]
No, I don‘t. Why?

**Comment by aadamsx** [comment]
Just wondering... as I'm using Autoform and this package doesn't seem to work with it is all... was hoping someone got it working.  I have an issue open from a long time back, but it's probably not a priority for him understandably.

**Comment by MartinKolb1987** [comment]
Hmm, sorry. Maybe I run into this problem later ;-).

**Comment by gabrielpoca** [comment]
Hi, I think I'm going to close this package in favor of [this](https://github.com/ccorcos/meteor-transitioner). You should have a look, it was inspired by my structure and I don't have the time to maintain mine.
