### ISSUE TITLE
Strange issue with bender and jade....?

### ISSUE THREAD

**Issue by sferoze** [subvisual/meteor-bender#6]
Hello,

I have traced this issue down to being related to the Bender package. If I remove the bender package the route and page loads like normal. 

This is the issue. I am using Bender with Iron Router.

So here is my layout file:

```
template(name='layout')
  +header
  .layout#content-container
    +yield
    //- Keep this coment here. It is needed for bender to work

  .slideshow-container#slideshow-container
```

You notice the jade comment. If I remove that comment Bender fails to load the page. So it looks like I need to keep the comment under the yield in order for Bender to work. Any idea why? I am using the fadeIn animation. 

Without the comment iron router does not even load the template into the yield spot. When I inspect in the DOM nothing is loading, the layout container is empty.

**Comment by aadamsx** [comment]
You should check out https://github.com/ccorcos/meteor-transitioner, as the owner of this package doesn't have the time to maintain it as per issue #5.
